MovieTicketApp_MVC_project/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieTicketApp_MVC_project.Data;
using MovieTicketApp_MVC_project.Data.Services;
using MovieTicketApp_MVC_project.Models;

namespace MovieTicketApp_MVC_project.Controllers
{
    
    public class ActorsController : Controller
    {
        public IActorsService _services;

        public ActorsController(IActorsService services)
        {
            _services = services;
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            var data = await _services.GetAll();
              return View(data);
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var actors = await  _services.GetById(id);
           

            if (actors == null)
            {
                return View("NotFound");
            }
            return View(actors);
        }
        //-----------------------start of image-----------------------//
        public async Task<FileContentResult>GetImage(int id)
        {
            var data = await  _services.GetAll();
            var model =  data.FirstOrDefault(x => x.Id == id);
               // .FirstOrDefaultAsync(m => m.Id == id);
            string imagePath = model.ProfilepictureURL;
            byte[] imageData = System.IO.File.ReadAllBytes(imagePath);
          return File(imageData, "image/jpeg");
        }
        //-------------------------end of image---------------------//

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public async Task<IActionResult> Create([Bind("Id,ProfilepictureURL,FullName,Bio")] Actor actor)
        {
            if (ModelState.IsValid)
            {
               await _services.Add(actor);
               
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        //GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _services.GetById(id);
            if (id == null || result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        //// POST: Actors/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilepictureURL,FullName,Bio")] Actor actor)
        {
            if (id != actor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                 await _services.Update(actor,id);
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        ////// GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var actor=await _services.GetById(id);
            if (id == null || actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        //// POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _services.GetById(id);

            if (actor == null)
            {
                return Problem("Entity set 'AppDbContext.Actors'  is null.");
            }

            await _services.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private Task<Actor> ActorExists(int id)
        {
            var actors = _services.GetAll();
            return _services.GetById(id);
        }
    }
}

MovieTicketApp_MVC_project/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using MovieTicketApp_MVC_project.Data;
using MovieTicketApp_MVC_project.Data.Enum;
using MovieTicketApp_MVC_project.Data.Services;
using MovieTicketApp_MVC_project.Data.ViewModels;
using MovieTicketApp_MVC_project.Models;

namespace MovieTicketApp_MVC_project.Controllers
{

    public class MoviesController : Controller
    {
        private readonly IMoviesService _context;

        public MoviesController(IMoviesService context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            var appDbContext =await _context.GetAll(m => m.Cinema,m =>m.Producer);
            
            return View( appDbContext);
        } 
        //Filter
        public async Task<IActionResult> Filter(string searchString)
        {
            var allMovies =await _context.GetAll(m => m.Cinema,m =>m.Producer);
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredMovie=allMovies.Where(n=>n.Name.ToUpper().Contains(searchString.ToUpper()) || n.Name.Contains(searchString.ToUpper())).ToList();
                return View("Index",filteredMovie);
            }

            return View("Index",allMovies);
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var movie = await _context.GetMovieByIdAsync(id);
            //if (movie == null)
            //{
            //    return NotFound();
            //}

            return View(movie);
        }

        // GET: Movies/Create
       
        public async Task< IActionResult> Create()
        {
            var movieDropdownsData = await _context.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas?? new List<Cinema>(), "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers ?? new List<Producer>(), "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors ?? new List<Actor>(), "Id", "FullName");
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,ImageURL,StartDate,EndDate,MovieCategory,ActorIds,CinemaId,ProducerId")] NewMovieVM movie)
        {
          
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _context.GetNewMovieDropdownsValues();
                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas ?? new List<Cinema>(), "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers ?? new List<Producer>(), "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors ?? new List<Actor>(), "Id", "FullName");
                return View(movie);
              
            }
            
            await _context.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));

        }

        // GET: Movies/Edit/5
      

        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _context.GetMovieByIdAsync(id);
            if (movieDetails == null) return NotFound();

            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),
            };
            var movieDropdownsData = await _context.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas ?? new List<Cinema>(), "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers ?? new List<Producer>(), "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors ?? new List<Actor>(), "Id", "FullName");

            return View(response);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  NewMovieVM movie)
        {
            if (id != movie.Id) return View("NotFound");
           

            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _context.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
                return View(movie);
            }
            await _context.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
            
        }

        // GET: Movies/Delete/5

        public async Task<IActionResult> Delete(int id)
        {
            var movie = await _context.GetById(id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.GetById(id);
            if (movie == null)
            {
                return Problem("Entity set 'AppDbContext.Movies'  is null.");
            }
            await _context.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private Task<Movie> MovieExists(int id)
        {
            var movies = _context.GetAll();
            return _context.GetById(id);
        }
        //-----------------------start of image-----------------------//
        public async Task<FileContentResult> GetImage(int id)
        {
            var data = await _context.GetAll();
            var model = data.FirstOrDefault(x => x.Id == id);
            // .FirstOrDefaultAsync(m => m.Id == id);
            string imagePath = model.ImageURL;
            byte[] imageData = System.IO.File.ReadAllBytes(imagePath);
            return File(imageData, "image/jpeg");
        }
        //-
    }
}

MovieTicketApp_MVC_project/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using MovieTicketApp_MVC_project.Data.Cart;
using MovieTicketApp_MVC_project.Data.Services;
using MovieTicketApp_MVC_project.Data.ViewModels;
using MovieTicketApp_MVC_project.Models;

namespace MovieTicketApp_MVC_project.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly IOrderService _orderService;
        private readonly ShoppingCart _shoppingCart;// from main class
       
        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }

        public async Task< IActionResult> Index()
        {
            string userId = "";
            var orders=await _orderService.GetOrdersByUserIdAsync(userId);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items=_shoppingCart.GetShoppingCartItems();//بجيب كل الايتمز اللى عندى فى الرئيسى
            _shoppingCart.ShoppingCartItems=items;//بحطهم فى متغير

            var result = new ShoppingCartVM()// create obj from vm class and == it to real obj
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal= _shoppingCart.GetShoppingCartTotal(),
            };
            return View(result);
        }



        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item=await _moviesService.GetMovieByIdAsync(id);
            if (item!=null) { _shoppingCart.AddItemToCart(item); }
            return RedirectToAction(nameof(ShoppingCart));

        }
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item=await _moviesService.GetMovieByIdAsync(id);

            if (item!=null) { _shoppingCart.RemoveItemFromCart(item); }

            return RedirectToAction(nameof(ShoppingCart));

        }
    
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string UserId = "";
            string UserEmailAddress = "";
            await _orderService.StoreOrderAsync(items, UserId, UserEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

MovieTicketApp_MVC_project/Views/Shared/NotFound.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
  import url("https://fonts.googleapis.com/css?family=Fira+Sans");
/*Variables*/
.left-section .inner-content {
  position: absolute;
  top: 50%;
/*  transform: translateY(-50%);
*/}

* {
/*  box-sizing: border-box;
*/
        margin: 0;
        padding: 0;
      
}

html, body {
    background-color:black;
  margin: 0;
  padding: 0;
        
    }

body {
        overflow-y: hidden;
  font-family: "Fira Sans", sans-serif;
  color: #f5f6fa;
/*  background-image: url("https://fonts.googleapis.com/css?family=Fira+Sans");
*/        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
}

.background {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: linear-gradient(#0C0E10, #446182);
}
.background .ground {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 25vh;
  background: #0C0E10;
}
media (max-width: 770px) {
  .background .ground {
    height: 0vh;
  }
}

.container {
  position: relative;
  margin: 0 auto;
  width: 95%;
  height: 100vh;
  padding-bottom: 25vh;
  display: flex;
  flex-direction: row;
  justify-content: space-around;
}
media (max-width: 770px) {
  .container {
    flex-direction: column;
    padding-bottom: 0vh;
  }
}

.left-section, .right-section {
  position: relative;
}

.left-section {
  width: 60%;
}
media (max-width: 770px) {
  .left-section {
    width: 100%;
    height: 40%;
    position: absolute;
    top: 0;
  }
}
media (max-width: 770px) {
  .left-section .inner-content {
    position: relative;
    padding: 1rem 0;
  }
}

.heading {
  text-align: center;
  font-size: 9em;
  line-height: 1.3em;
  margin: 2rem 0 0.5rem 0;
  padding: 0;
  text-shadow: 0 0 1rem lightblue;
}
media (max-width: 770px) {
  .heading {
    font-size: 7em;
    line-height: 1.15;
    margin: 0;
  }
}

.subheading {
  text-align: center;
  max-width: 680px;
  font-size: 2em;
  line-height: 1.15em;
  padding: 0 1rem;
  margin: 0 auto;
}
media (max-width: 770px) {
  .subheading {
    font-size: 1.3em;
    line-height: 1.15;
    max-width: 100%;
  }
}

.right-section {
  width: 50%;
}
media (max-width: 770px) {
  .right-section {
    width: 100%;
    height: 60%;
    position: absolute;
    bottom: 0;
  }
}

.svgimg {
  position: absolute;
  bottom: 0;
  padding-top: 10vh;
  padding-left: 1vh;
  max-width: 100%;
  max-height: 100%;
}
media (max-width: 770px) {
  .svgimg {
    padding: 0;
  }
}
.svgimg .bench-legs {
  fill: #0C0E10;
}
.svgimg .top-bench, .svgimg .bottom-bench {
  stroke: #0C0E10;
  stroke-width: 1px;
  fill: #5B3E2B;
}
.svgimg .bottom-bench path:nth-child(1) {
  fill: #432d20;
}
.svgimg .lamp-details {
  fill: #202425;
}
.svgimg .lamp-accent {
  fill: #2c3133;
}
.svgimg .lamp-bottom {
  fill: linear-gradient(#202425, #0C0E10);
}
.svgimg .lamp-light {
  fill: #EFEFEF;
}

keyframes glow {
  0% {
    text-shadow: 0 0 1rem #fefefe;
  }
  50% {
    text-shadow: 0 0 1.85rem #ededed;
  }
  100% {
    text-shadow: 0 0 1rem #fefefe;
  }
}
</style>
<div class="background">
    <div class="ground"></div>
</div>
<div class="container">
    <div class="left-section">
        <div class="inner-content">
            <h1 class="heading">404</h1>
            <p class="subheading">Looks like the page you were looking for is no longer here.</p>
        </div>
    </div>
    <div class="right-section">
        <svg class="svgimg" xmlns="http://www.w3.org/2000/svg" viewBox="51.5 -15.288 385 505.565">
            <g class="bench-legs">
                <path d="M202.778,391.666h11.111v98.611h-11.111V391.666z M370.833,390.277h11.111v100h-11.111V390.277z M183.333,456.944h11.111
          v33.333h-11.111V456.944z M393.056,456.944h11.111v33.333h-11.111V456.944z" />
            </g>
            <g class="top-bench">
                <path d="M396.527,397.917c0,1.534-1.243,2.777-2.777,2.777H190.972c-1.534,0-2.778-1.243-2.778-2.777v-8.333
          c0-1.535,1.244-2.778,2.778-2.778H393.75c1.534,0,2.777,1.243,2.777,2.778V397.917z M400.694,414.583
          c0,1.534-1.243,2.778-2.777,2.778H188.194c-1.534,0-2.778-1.244-2.778-2.778v-8.333c0-1.534,1.244-2.777,2.778-2.777h209.723
          c1.534,0,2.777,1.243,2.777,2.777V414.583z M403.473,431.25c0,1.534-1.244,2.777-2.778,2.777H184.028
          c-1.534,0-2.778-1.243-2.778-2.777v-8.333c0-1.534,1.244-2.778,2.778-2.778h216.667c1.534,0,2.778,1.244,2.778,2.778V431.25z" />
            </g>
            <g class="bottom-bench">
                <path d="M417.361,459.027c0,0.769-1.244,1.39-2.778,1.39H170.139c-1.533,0-2.777-0.621-2.777-1.39v-4.86
          c0-0.769,1.244-0.694,2.777-0.694h244.444c1.534,0,2.778-0.074,2.778,0.694V459.027z" />
                <path d="M185.417,443.75H400c0,0,18.143,9.721,17.361,10.417l-250-0.696C167.303,451.65,185.417,443.75,185.417,443.75z" />
            </g>
            <g id="lamp">
                <path class="lamp-details" d="M125.694,421.997c0,1.257-0.73,3.697-1.633,3.697H113.44c-0.903,0-1.633-2.44-1.633-3.697V84.917
          c0-1.257,0.73-2.278,1.633-2.278h10.621c0.903,0,1.633,1.02,1.633,2.278V421.997z" />
                <path class="lamp-accent" d="M128.472,93.75c0,1.534-1.244,2.778-2.778,2.778h-13.889c-1.534,0-2.778-1.244-2.778-2.778V79.861
          c0-1.534,1.244-2.778,2.778-2.778h13.889c1.534,0,2.778,1.244,2.778,2.778V93.75z" />

                <circle class="lamp-light" cx="119.676" cy="44.22" r="40.51" />
                <path class="lamp-details" d="M149.306,71.528c0,3.242-13.37,13.889-29.861,13.889S89.583,75.232,89.583,71.528c0-4.166,13.369-13.889,29.861-13.889
          S149.306,67.362,149.306,71.528z" />
                <radialGradient class="light-gradient" id="SVGID_1_" cx="119.676" cy="44.22" r="65" gradientUnits="userSpaceOnUse">
                    <stop offset="0%" style="stop-color:#FFFFFF; stop-opacity: 1" />
                    <stop offset="50%" style="stop-color:#EDEDED; stop-opacity: 0.5">
                        <animate attributeName="stop-opacity" values="0.0; 0.5; 0.0" dur="5000ms" repeatCount="indefinite"></animate>
                    </stop>
                    <stop offset="100%" style="stop-color:#EDEDED; stop-opacity: 0" />
                </radialGradient>
                <circle class="lamp-light__glow" fill="url(#SVGID_1_)" cx="119.676" cy="44.22" r="65" />
                <path class="lamp-bottom" d="M135.417,487.781c0,1.378-1.244,2.496-2.778,2.496H106.25c-1.534,0-2.778-1.118-2.778-2.496v-74.869
          c0-1.378,1.244-2.495,2.778-2.495h26.389c1.534,0,2.778,1.117,2.778,2.495V487.781z" />
            </g>
        </svg>
    </div>
</div>

MovieTicketApp_MVC_project/Views/Shared/_CreateItem.cshtml
@model string;


<div class="text-white" style="position:fixed;right:25px;bottom:25px;">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-outline-warning"><i class="bi bi-plus-circle"></i>Add New</a>
</div>

MovieTicketApp_MVC_project/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-info my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{

    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-warning dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
          <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
       </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

MovieTicketApp_MVC_project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eTickets.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  bg-black border-bottom box-shadow mb-3 text-light">
            <div class="container-fluid">
                <a class="navbar-brand " asp-area="" asp-controller="Movies" asp-action="Index"><img src="~/Images/logo3.jpeg" width="90px" height="70px" style="border-radius:50%" /></a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">  

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Movies" asp-action="Index"><i class="badge-info bi-film"></i> Movies</a>
                        </li>

                        @*Dropdown*@
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-gear"></i> Management
                            </a>
                          
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinema</a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                            </div>
                        </li>
                        }
                    </ul>

                      @*Search Btn*@
                        <form class="row" asp-controller="Movies" asp-action="Filter">
                            <input name="searchString" type="text" class="col-8 mx-2" placeholder="Search for a movie...">
                            <button class="btn btn-outline-warning col-2" type="submit"><i class="bi bi-search"></i></button>
                        </form>
                        
                        @*Cart Icon*@
                        <ul class="navbar-nav">
                           @await Component.InvokeAsync("ShoppingCartSummary")
                        </ul>

                       @* Login Icon
                        <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
                            <i class="bi bi-box-arrow-in-right">Log in</i>
                        </a> 
                        Sign up Icon
                        <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
                            <i class="bi bi-box-person-plus">Sign up</i>
                    </a>*@
@*                            <li class="nav-item dropdown btn btn-outline-success">
                        <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-person-badge"></i> Hello User
                                </a>
                                <div class="dropdown-menu" aria-labelledby="profile-btn">
                                    <a class="dropdown-item" asp-controller="Orders" asp-action="Index"> 
                                        <i class="bi bi-list"></i>Orders 
                                        </a>
                                 </div>
                            </li>
*@
                    <partial name="_Identity.cshtml" />

            @*      <span style="padding:5px"></span>
                    <form asp-controller="Account" asp-action="Logout">
                        <button class="btn btn-outline-danger my-2">
                            <i class="bi bi-box-arrow-in-right"></i>Logout
                        </button>
                    </form>*@
                    
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - eTickets
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>