MovieTicketApp_MVC_project/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieTicketApp_MVC_project.Data;
using MovieTicketApp_MVC_project.Data.Services;
using MovieTicketApp_MVC_project.Models;

namespace MovieTicketApp_MVC_project.Controllers
{
    
    public class ActorsController : Controller
    {
        public IActorsService _services;

        public ActorsController(IActorsService services)
        {
            _services = services;
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            var data = await _services.GetAll();
              return View(data);
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var actors = await  _services.GetById(id);
           

            if (actors == null)
            {
                return View("NotFound");
            }
            return View(actors);
        }
        //-----------------------start of image-----------------------//
        public async Task<FileContentResult>GetImage(int id)
        {
            var data = await  _services.GetAll();
            var model =  data.FirstOrDefault(x => x.Id == id);
               // .FirstOrDefaultAsync(m => m.Id == id);
            string imagePath = model.ProfilepictureURL;
            byte[] imageData = System.IO.File.ReadAllBytes(imagePath);
          return File(imageData, "image/jpeg");
        }
        //-------------------------end of image---------------------//

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public async Task<IActionResult> Create([Bind("Id,ProfilepictureURL,FullName,Bio")] Actor actor)
        {
            if (ModelState.IsValid)
            {
               await _services.Add(actor);
               
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        //GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _services.GetById(id);
            if (id == null || result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        //// POST: Actors/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilepictureURL,FullName,Bio")] Actor actor)
        {
            if (id != actor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                 await _services.Update(actor,id);
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        ////// GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var actor=await _services.GetById(id);
            if (id == null || actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        //// POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _services.GetById(id);

            if (actor == null)
            {
                return Problem("Entity set 'AppDbContext.Actors'  is null.");
            }

            await _services.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private Task<Actor> ActorExists(int id)
        {
            var actors = _services.GetAll();
            return _services.GetById(id);
        }
    }
}

MovieTicketApp_MVC_project/Controllers/CinemasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieTicketApp_MVC_project.Data;
using MovieTicketApp_MVC_project.Models;

namespace MovieTicketApp_MVC_project.Controllers
{
    public class CinemasController : Controller
    {
        private readonly AppDbContext _context;

        public CinemasController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Cinemas
        public async Task<IActionResult> Index()
        {
              return View(await _context.Cinemas.ToListAsync());
        }

        // GET: Cinemas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cinemas == null)
            {
                return NotFound();
            }

            var cinema = await _context.Cinemas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cinema == null)
            {
                return NotFound();
            }

            return View(cinema);
        }

        // GET: Cinemas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cinemas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cinema);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        // GET: Cinemas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cinemas == null)
            {
                return NotFound();
            }

            var cinema = await _context.Cinemas.FindAsync(id);
            if (cinema == null)
            {
                return NotFound();
            }
            return View(cinema);
        }

        // POST: Cinemas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (id != cinema.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cinema);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CinemaExists(cinema.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        // GET: Cinemas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cinemas == null)
            {
                return NotFound();
            }

            var cinema = await _context.Cinemas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cinema == null)
            {
                return NotFound();
            }

            return View(cinema);
        }

        // POST: Cinemas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cinemas == null)
            {
                return Problem("Entity set 'AppDbContext.Cinemas'  is null.");
            }
            var cinema = await _context.Cinemas.FindAsync(id);
            if (cinema != null)
            {
                _context.Cinemas.Remove(cinema);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CinemaExists(int id)
        {
          return _context.Cinemas.Any(e => e.Id == id);
        }
    }
}

MovieTicketApp_MVC_project/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using MovieTicketApp_MVC_project.Data.Cart;
using MovieTicketApp_MVC_project.Data.Services;
using MovieTicketApp_MVC_project.Data.ViewModels;
using MovieTicketApp_MVC_project.Models;

namespace MovieTicketApp_MVC_project.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly IOrderService _orderService;
        private readonly ShoppingCart _shoppingCart;// from main class
       
        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }

        public async Task< IActionResult> Index()
        {
            string userId = "";
            var orders=await _orderService.GetOrdersByUserIdAsync(userId);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items=_shoppingCart.GetShoppingCartItems();//بجيب كل الايتمز اللى عندى فى الرئيسى
            _shoppingCart.ShoppingCartItems=items;//بحطهم فى متغير

            var result = new ShoppingCartVM()// create obj from vm class and == it to real obj
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal= _shoppingCart.GetShoppingCartTotal(),
            };
            return View(result);
        }



        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item=await _moviesService.GetMovieByIdAsync(id);
            if (item!=null) { _shoppingCart.AddItemToCart(item); }
            return RedirectToAction(nameof(ShoppingCart));

        }
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item=await _moviesService.GetMovieByIdAsync(id);

            if (item!=null) { _shoppingCart.RemoveItemFromCart(item); }

            return RedirectToAction(nameof(ShoppingCart));

        }
    
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string UserId = "";
            string UserEmailAddress = "";
            await _orderService.StoreOrderAsync(items, UserId, UserEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

MovieTicketApp_MVC_project/Controllers/ProducersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieTicketApp_MVC_project.Data;
using MovieTicketApp_MVC_project.Data.Services;
using MovieTicketApp_MVC_project.Models;

namespace MovieTicketApp_MVC_project.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducersService _context;

        public ProducersController(IProducersService context)
        {
            _context = context;
        }

        // GET: Producers
        public async Task<IActionResult> Index()
        {
              return View(await _context.GetAll());
        }

        // GET: Producers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var producer = await _context.GetById(id);
            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }

        // GET: Producers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Producers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProfilepictureURL,FullName,Bio")] Producer producer)
        {
            if (!ModelState.IsValid) return View(producer);
           
            await _context.Add(producer);
            return RedirectToAction(nameof(Index));
         
            
        }

        // GET: Producers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var producer = await _context.GetById(id);
            if (producer == null)
            {
                return NotFound();
            }
            return View(producer);
        }

        // POST: Producers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilepictureURL,FullName,Bio")] Producer producer)
        {
            if (id != producer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _context.Update(producer, id);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        // GET: Producers/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var producer =await _context.GetById(id);
            if (id == null ||producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }

        // POST: Producers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _context.GetById(id);

            if (actor == null)
            {
                return Problem("Entity set 'AppDbContext.Producers'  is null.");
            }

            await _context.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private Task<Producer> ProducerExists(int id)
        {

            //var producers = _context.GetAll();
            return _context.GetById(id);
        }
    }
}

MovieTicketApp_MVC_project/Views/Movies/Create.cshtml
@using MovieTicketApp_MVC_project.Data.Enum;
@model MovieTicketApp_MVC_project.Data.ViewModels.NewMovieVM

@{
    ViewData["Title"] = "Create new movie";
}
<div class="row">
    <div class="col-md-8 offset-2 text-light">
        <p>
            <h4>Create a new movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCategory" class="control-label"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                           @* <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>*@
                            <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center my-2" style="height:100px">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group d-flex justify-content-between">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>
<div id="icon">
    <i class="bi bi-film"></i>
</div>

@section Scripts{
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}
@*<div class="row text-light">
    <div class="col-md-4 ">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieCategory" class="control-label"></label>
                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                <span asp-validation-for="MovieCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CinemaId" class="control-label"></label>
                <select asp-for="CinemaId" class ="form-control" asp-items="ViewBag.CinemaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProducerId" class="control-label"></label>
                <select asp-for="ProducerId" class ="form-control" asp-items="ViewBag.ProducerId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div >
    <a asp-action="Index">Back to List</a>
</div>
<div id="icon">
    <i class="bi bi-film"></i>
</div>*@



<style>
    body {
        overflow-y: hidden;
        overflow-x:hidden;
        
    }
    #icon
    {
        color:floralwhite;
        -webkit-transform: rotate(45deg);
        transform: rotate(45deg);
        font-size:430px;
        position: relative;
        top: 0;
        left:70%;

       
    }
/*input{
    margin-top:5px;
}
label{
    margin-top:10px;
}*/
</style>

MovieTicketApp_MVC_project/Views/Movies/Details.cshtml
@model MovieTicketApp_MVC_project.Models.Movie

@{
    ViewData["Title"] = "Details";
}

<style>
    body,html{
        background-image: url('@Model.ImageURL');
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
       
    }
</style>
@*<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                       

                        
                       
                        


                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var actor in Model.Actors_Movies)
                                {
                                    <div class="column text-center">
                                        <br />
                                        <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.ActorId">
                                            <img class="border-info rounded" src="@actor.Actor.ProfilepictureURL" style="max-width: 150px" />
                                        </a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
               
            </div>
        </div>
    </div>
</div>
*@
<div id="card">


    <h1 class="text-light my-5" style="text-shadow: 2px 2px black;">@Model.Name</h1>
<p class="card-text text-light"><b>Category: </b>@Model.MovieCategory</p>
<p class="card-text ">
    @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
    {
        <span class="badge bg-success text-white">AVAILABLE</span>
    }
    else if (DateTime.Now > Model.EndDate)
    {
        <span class="badge bg-danger text-white">EXPIRED</span>
    }
    else
    {
        <span class="badge bg-primary text-white">UPCOMING</span>
    }
</p>
<div class="row my-2 text-light">
    <p class="card-text col-6"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
    <p class="card-text col-6"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
</div>


<div class="row">
    <p class="card-text col-6">
        <b class="text-light">Cinema: </b>
        <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.CinemaId" class="text-warning text-decoration-none">
            @Model.Cinema.Name
        </a>
    </p>
    <p class="card-text col-6">
            <b class="text-light">Producer: </b>
        <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId" class="text-warning text-decoration-none">
            @Model.Producer.FullName
        </a>
    </p>
</div>




<div class="card-body my-4" style="max-width:90%; max-height:15%;">
    <p class="card-text text-light">@Model.Description</p>
    </div>



<div class="col-md-12">
    <div class="card-footer">
        <p class="card-text">
            <a class="btn btn-outline-primary float-right" asp-action="Index">
                Back to List
            </a>
            <a class="btn btn-success text-white  @((DateTime.Now > Model.EndDate) ? "disabled" : "")"
               asp-controller="Orders"
               asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>
        </p>
    </div>
</div>
</div>
<style>
    #card{
        box-shadow: 0 0 5px 0;
        background: inherit;
        backdrop-filter: blur(5px);
        margin-top:5%;
        margin-right:50%;
        border-radius: 20px;
        padding:10px;
        width: 50%;
        box-shadow: 5px 5px 15px white;
    }
</style>

MovieTicketApp_MVC_project/Views/Movies/Index.cshtml
@model IEnumerable<MovieTicketApp_MVC_project.Models.Movie>

@{
    ViewData["Title"] = "Index";
}

<style>
  /*  .bi.bi-x-octagon:hover {
        color: #f44336 !important;
        
    }

    .bi.bi-bag-plus-alt:hover {
        color: #0d47a1 !important;
    }*/
    h5,p{
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
    }
    a{
        text-decoration:none;
    }
    #main{
        width: 28rem;
        height: 38rem;
        box-shadow: 1px 4px 10px #4D4D4D;
    }

</style>

<div class="row d-flex justify-content-between ">
    @foreach (var item in Model)
  {
        <div id="main" class="card bg-black rounded my-3">
      
                <div class="my-2">
                    <h5 class="card-title font-weight-bold text-warning mx-2">
                         <a asp-action="Edit" asp-route-id="@item.Id">
                        <i class="bi bi-pen text-warning my-1" title="Edit"></i>
                    </a> @item.Name
                </h5>
                  
                </div>


            <img class="h-75" src="@item.ImageURL" alt="Card image cap" />


           <div class="card-body">
                @*---------------------------------------------------------*@
                <p class="card-text text-secondary" id="c">@item.Description</p>
                @*---------------------------------------------------------*@
                <div class="d-flex justify-content-end">
                 <a href="#" class="btn btn-link text-muted mr-5 "></a>                    
                        <a asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id">
                            <i class="bi bi-bag-plus text-light mx-1" data-mdb-toggle="tooltip"
                           data-mdb-placement="top" title="Add to card"></i>
                           </a>
                        <a asp-action="Details" asp-route-id="@item.Id">
                        <i class="bi bi-three-dots-vertical text-light mx-1" data-mdb-toggle="tooltip" data-mdb-placement="top" title="Show details"></i>
                        </a> 
                        <a asp-action="Delete" asp-route-id="@item.Id">
                            <i class="bi bi-x-octagon text-danger mx-1" data-mdb-toggle="tooltip" data-mdb-placement="top" title="Delete"></i>
                        </a>

                  
                </div>
            </div>
   
</div>
  }
  </div>


    @await Html.PartialAsync("_CreateItem","Movies");